version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: TesteL2/Dockerfile
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=teste_tecnico_L2;User=sa;Password=password@123;TrustServerCertificate=True;Encrypt=False
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=password@123
      - ACCEPT_EULA=Y
    ports:
      - "8002:1433"
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata: